[build]
  publish = "public"
  command = "hugo --minify --buildFuture"

[build.environment]
  HUGO_VERSION = "0.161.1"
  HUGO_ENV = "production"

[[redirects]]
  from = "/wp-content/uploads/*"
  to = "/img/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://insidethatad.com/*"
  to = "https://www.insidethatad.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.insidethatad.com/*"
  to = "https://www.insidethatad.com/:splat"
  status = 301
  force = true

[context.production]
  command = "hugo --minify --buildFuture"

[context.deploy-preview]
  command = "hugo --buildDrafts --minify"
